=== NielsHamelryck/VDAB-Opleiding/XML Fundamentals/XMLtest/PersonenSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
xmlns:vdab="http://www.vdab.be/personen"
targetNamespace="http://www.vdab.be/personen" elementFormDefault="qualified">
  <!--
  
  lijst van attributen
    persoonnr  positiveInteger
  
  lijst van elementen
    voornaam vdab:NamenControle
    familienaam vdab:NamenControle
    email   vdab:EmailControle
    geboorteDatum vdab:GeboortedatumControle
    traject vdab:TrajectControle
    
  -->

  <simpleType name ="NamenControle">
    <restriction base ="string">
      <pattern value ="^[^\s]+.{0,}"/>
    </restriction>
  </simpleType>
  <simpleType name="EmailControle">
    <restriction base="string">
      <pattern value="^.+@.+\.[a-z]+$"/>
    </restriction>
  </simpleType>
  <simpleType name="GeboortedatumControle">
    <restriction base ="date">
      <minInclusive value="1950-01-01"/>
    </restriction>
  </simpleType>
  <simpleType name="TrajectControle">
    <restriction base="string">
      <pattern value ="^(Java|C#|PHP)$"/>
    </restriction>
  </simpleType>
  <complexType name="Persoon">
    <sequence>
      <element name="voornaam" type="vdab:NamenControle"/>
      <element name="Familienaam" type="vdab:NamenControle"/>
      <element name="email" type="vdab:EmailControle"/>
      <element name="geboorteDatum" type="vdab:GeboortedatumControle"/>
      <element name="traject" type="vdab:TrajectControle"/>
    </sequence>
    <attribute name ="persoonnr"  use="required" type="positiveInteger"/>
  </complexType>
  <complexType name="Personen">
    <sequence>
      <element name="persoon" minOccurs ="0" maxOccurs="unbounded" type="vdab:Persoon"/>
    </sequence>
  </complexType>
  <element name ="personen" type="vdab:Personen">
    <key name ="persoonKey">
      <selector xpath ="vdab:persoon"/>
      <field xpath ="@persoonnr"/>
    </key>
    <key name ="emailKey">
      <selector xpath ="vdab:persoon"/>
      <field xpath ="vdab:email"/>
    </key>
  </element>
</schema>

=== NielsHamelryck/VDAB-Opleiding/XML Fundamentals/XMLtest/Personen.xml
<?xml version="1.0" encoding="utf-8"?>
<personen xmlns="http://www.vdab.be/personen"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation ="http://www.vdab.be/personen personenschema.xsd">
  <persoon persoonnr="1">
    <voornaam>Joe</voornaam>
    <Familienaam>Dalton</Familienaam>
    <email>joe@daltons.org</email>
    <geboorteDatum>1966-08-01</geboorteDatum>
    <traject>Java</traject>
  </persoon>
  <persoon persoonnr="2">
    <voornaam>Jack</voornaam>
    <Familienaam>Dalton</Familienaam>
    <email>jack@daltons.org</email>
    <geboorteDatum>1964-08-28</geboorteDatum>
    <traject>C#</traject>
  </persoon>
  <persoon persoonnr="3">
    <voornaam>Lucky</voornaam>
    <Familienaam>Luke</Familienaam>
    <email>Lucky.Luke@goodones.org</email>
    <geboorteDatum>1965-01-31</geboorteDatum>
    <traject>PHP</traject>
  </persoon>
</personen>
